version: 2

sources:
  - name: ecom_raw
    database: ecom-demo-488710
    schema: ecom_raw
    tables:
      - name: orders
      - name: customers
      - name: products
      - name: order_refunds
      - name: product_variants
